name: CI   
                
on:
  push:
  workflow_dispatch:
                              
jobs:                        
  build:                     
    runs-on: macos-13
                              
    steps:                   
    - uses: actions/checkout@v2                                           
                              
    - name: Set Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
                              
                              
    - name: Build Cork App   
      run: |                 
        xcodebuild -scheme Cork -configuration Release -archivePath Cork.xcarchive archive -arch x86_64
        xcodebuild -exportArchive -archivePath Cork.xcarchive -exportPath CorkApp -exportOptionsPlist ExportOptions.plist
                              
    - name: Upload Artifact  
      uses: actions/upload-artifact@v3                                  
      with:                  
        name: Cork.app    
        path: CorkApp/Cork.app

    - name: Update Nightly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: 'Cork App Nightly Release $$'
        prerelease: true
        body: 'TODO: Add nightly release notes'
        files: |
          CorkApp/Cork.app
          